bl_alpha: 0.05
bl_warmup_epochs: 1
checkpoint_encoder: false
checkpoint_epochs: 1
data_distribution: null
device: cuda:0
epoch_start: 0
eval_only: false
exp_beta: 0.8
wandb_disabled: false

batch_size: 100
eval_batch_size: 100
graph_size: 100
#train_epoch_size: 50000
train_epoch_size: 1280000
val_epoch_size: 10000
buffer_size: 12000
n_epochs: 100

#alg:
#  type: ac
#  args:
#    loss_weights:
#      - 1.0
#      - 1.0
#      - 0.0
#    max_grad_norm: 1.0
#    gamma: 1.0
alg:
  type: pg_rollout
  args:
    loss_weights:
      - 1.0
      - 0.0
      - 0.5
    max_grad_norm: 1.0
    gamma: 1

agent:
  encoder:
    cls: AgentGNN
    args:
      input_dim: 32
      hidden_dim: 32
      out_dim: 128
      dropout: 0
      num_agents: 30
      num_steps: 16
      node_readout: true
      bptt_steps: 8
      gate: true
      temp: 0.666
#      temp: [0.3, 0.666]
  embedding_dim: 32
  hidden_dim: 128
  ff_hidden_dim: 256
  n_heads: 8
  num_layers: 2
  dropout: 0
  node_features_option: once # once, update, always

log_dir: logs
log_step: 1000

lr_actor: 0.00001
lr_critic: 0.00001
lr_encoder: 0.00001
lr_min_decay: 0.25
lr_decay: 1
weight_decay: 0.05
no_progress_bar: false
normalization: batch
#output_dir: outputs
problem: cvrp
resume: null
save_dir: outputs
seed: 1234
shrink_size: null
tanh_clipping: 10.0
val_dataset: null
num_workers: 4